language: ruby

rvm:
- 2.4.1

install:
- bundle install
- gem install jekyll
- gem install jekyll-feed
- gem install jekyll-paginate
- gem install html-proofer

branches:
  only:
  - master

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email:
    recipients:
    - sulantha.s@gmail.com
    on_success: always
    on_failure: always

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html

addons:
  ssh_known_hosts: nrm2020.org

before_deploy:
- openssl aes-256-cbc -K $encrypted_5cd308d051d7_key -iv $encrypted_5cd308d051d7_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site/ build@nrm2020.org:/home/build/nrm2020/
  on:
    branch: master
