language: ruby
rvm:
- 2.3.1
install:
- bundle install
- gem install jekyll
- gem install jekyll-feed
- gem install jekyll-paginate
- gem install html-proofer
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
    - sulantha.s@gmail.com
    on_success: always
    on_failure: always
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
after_success:
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_5cd308d051d7_key -iv $encrypted_5cd308d051d7_iv
  -in deploy_rsa.enc -out deploy_rsa -d
